name: Build C++ EXE (MSVC)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2022buildtools --params "'/Add Microsoft.VisualStudio.Workload.VCTools /Quiet /NoRestart'" -y

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild "XC Bypass.sln" /p:Configuration=Release /p:Platform=x64

    - name: Upload Built EXE
      uses: actions/upload-artifact@v4
      with:
        name: XC-Bypass-EXE
        path: |
          **/x64/Release/*.exe
          **/Release/*.exe
